@url = http://localhost:8080/api/goal
@token= eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnb2Fscy1saXN0Iiwic3ViIjoic2FsbHlAam9uZXMuY29tIiwiYXBwX3VzZXJfaWQiOjIsImF1dGhvcml0aWVzIjoiVVNFUiIsImV4cCI6MTY4OTMwMDY3MH0.4G3KTfzIN-wqJl9m0M9msKt-VZIdC0BwiKDFG6TztnM

GET {{url}}/2 HTTP/1.1
Authorization: Bearer {{token}}

###

GET {{url}}/user/2 HTTP/1.1
Authorization: Bearer {{token}}

###

POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "RESTTest",
    "checked": true,
    "reason": "reason test",
    "realisticDeadline": "fake date",
    "ambitiousDeadline": "fake date",
    "appUserId": 2
}